categories = {
"Eletrônicos": ["Celulares", "Smartphones", "Tablets", "Laptops", "Desktops", "Monitores", "Televisores", "Câmeras Digitais", "Filmadoras", "Acessórios (carregadores, cabos, cases)"],
"Áudio & Fones": ["Fone de Ouvido In-Ear", "Headset Over-Ear", "Earbuds True Wireless", "Caixas de Som Bluetooth", "Soundbar", "Microfones", "Metronomos & Tuner"],
"Fotografia & Vídeo": ["Lentes", "Tripés", "Gimbals", "Iluminação (softbox, ring light)", "Cartões de Memória", "Bolsas & Mochilas para Câmera"],
"Relógios & Wearables": ["Relógio de Pulso", "Smartwatch", "Pulseira Esportiva"],
"Acessórios Pessoais": ["Óculos de Sol", "Bonés & Chapéus", "Cintos", "Luvas"],
"Bolsas & Malas": ["Mochilas", "Malas de Viagem", "Bolsas de Mão", "Pochetes", "Maletas/Briefcases"],
"Roupas": ["Camisetas", "Camisas", "Jaquetas & Casacos", "Vestidos", "Calças & Jeans", "Shorts", "Moletons", "Uniformes/Esportivas"],
"Calçados": ["Tênis", "Botas", "Sandálias/Chinelos", "Sapatos Sociais"],
"Casa & Cozinha": ["Panelas", "Chaleiras", "Liquidificadores", "Batedeiras", "Torradeiras", "Cafeteiras", "Forno Micro-ondas", "Aspiradores de Pó", "Ferro de Passar", "Luminárias/Abajures"],
"Ferramentas & Construção": ["Furadeiras", "Parafusadeiras", "Lixadeiras", "Motosserras", "Martelos", "Chaves de Fenda", "Alicate", "Trenas", "Níveis"],
"Jardinagem": ["Cortador de Grama", "Soprador", "Tesoura de Poda", "Mangueiras", "Regadores"],
"Esporte & Fitness": ["Bicicletas", "Dumbbells/Halteres", "Kettlebells", "Bolas (Futebol, Basquete, Tênis)", "Skate", "Patins", "Capacetes & Protetores"],
"Instrumentos Musicais": ["Violão", "Guitarra", "Baixo", "Teclado/Piano", "Violino", "Bateria/Pratos", "Amplificadores", "Pedais de Efeito"],
"Automotivo": ["Acessórios Internos", "Acessórios Externos", "Pneus/Rodas", "Capas & Organizadores", "Baterias & Cabos"],
"Moto & Bike": ["Capacetes", "Luzes & Lanternas", "Bombas de Ar", "Cadeados", "Suportes de Garrafa", "Selins & Pedais"],
"Brinquedos & Hobbies": ["Urso de Pelúcia", "Bonecos/Action Figures", "Quebra-cabeças", "Carrinhos", "Drones básicos", "Kits de Arte"],
"Papelaria & Escritório": ["Teclados", "Mouses", "Impressoras", "Scanners", "Webcams", "Headsets para PC", "Organizadores", "Cadernos & Canetas"],
"Segurança & Acessórios": ["Cadeados", "Travas para Bicicleta", "Fechaduras", "Câmeras Básicas de Segurança"],
"Pet Shop & Acessórios": ["Coleiras/Guias", "Comedouros & Bebedouros", "Brinquedos para Pets", "Camas & Casinhas", "Rasqueadeiras"],
"Alimentos & Bebidas (Imagem)": ["Frutas (Banana, Maçã, Laranja, Morango)", "Snacks (Batata, Pipoca)", "Lanches (Hambúrguer, Hot Dog, Pizza)", "Sorvetes/Picolés", "Bebidas Enlatadas"],
"Náutica & Ar Livre": ["Barcos Infláveis", "Caiaques Básicos", "Coletes Salva-Vidas", "Bússolas"],
"Aviões/Trens/Brinquedos de Veículos": ["Aviões de Brinquedo", "Trens em Miniatura", "Helicópteros de Brinquedo"]
}